import { chromium } from 'playwright-core';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage();
page.on('console', m => console.log('PAGE LOG:', m.text()));
await page.setContent('<!doctype html><html><body><iframe sandbox="allow-same-origin"></iframe></body></html>');
const inner = '<script>window.__nestedRan=1;</script>';
const outer = '<!doctype html><html><body><iframe id=nested sandbox="allow-scripts allow-same-origin" srcdoc="' + inner.replace(/\"/g,'&quot;') + '"></iframe></body></html>';
await page.evaluate((html) => { document.querySelector('iframe').srcdoc = html; }, outer);
await page.waitForTimeout(700);
const frames = page.frames();
console.log('frame count', frames.length, frames.map(f=>f.url()));
const nested = frames[frames.length - 1];
const r = await nested.evaluate(() => !!window.__nestedRan).catch(e => 'ERR:' + e.message);
console.log('nested script ran:', r);
await browser.close();
